//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tna.SAllocatePlus.CommonShared.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetPasswordRequestDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class ResetPasswordRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NewPasswordField;
        
        private string OldPasswordField;
        
        private int UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldPassword
        {
            get
            {
                return this.OldPasswordField;
            }
            set
            {
                this.OldPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffAccountDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class StaffAccountDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Tna.SAllocatePlus.CommonShared.Dto.AccessRightsDto[] AccessListField;
        
        private bool ActiveField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string MobileField;
        
        private string[] RoleListField;
        
        private string StaffCostCentreField;
        
        private int StaffIDField;
        
        private string SurNameField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tna.SAllocatePlus.CommonShared.Dto.AccessRightsDto[] AccessList
        {
            get
            {
                return this.AccessListField;
            }
            set
            {
                this.AccessListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RoleList
        {
            get
            {
                return this.RoleListField;
            }
            set
            {
                this.RoleListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffCostCentre
        {
            get
            {
                return this.StaffCostCentreField;
            }
            set
            {
                this.StaffCostCentreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffID
        {
            get
            {
                return this.StaffIDField;
            }
            set
            {
                this.StaffIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurName
        {
            get
            {
                return this.SurNameField;
            }
            set
            {
                this.SurNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessRightsDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class AccessRightsDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Tna.SAllocatePlus.CommonShared.AccessRightsEnum AccessRightsField;
        
        private string CostCentreCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tna.SAllocatePlus.CommonShared.AccessRightsEnum AccessRights
        {
            get
            {
                return this.AccessRightsField;
            }
            set
            {
                this.AccessRightsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCentreCode
        {
            get
            {
                return this.CostCentreCodeField;
            }
            set
            {
                this.CostCentreCodeField = value;
            }
        }
    }
}
namespace Tna.SAllocatePlus.CommonShared
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessRightsEnum", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared")]
    public enum AccessRightsEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 3,
    }
}

