//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tna.SAllocatePlus.CommonShared.Dto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class JobDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookIDField;
        
        private System.Nullable<bool> EmailSentField;
        
        private string JobCostCentreField;
        
        private System.Nullable<System.DateTime> JobDateField;
        
        private string JobDetailsField;
        
        private Tna.SAllocatePlus.CommonShared.Dto.JobStaffDto[] JobStaffListField;
        
        private Tna.SAllocatePlus.CommonShared.JobStageEnum JobStageField;
        
        private System.Nullable<System.TimeSpan> JobTimeField;
        
        private string SiteAddressField;
        
        private string SiteNameField;
        
        private int StaffRequiredField;
        
        private string SupervisorNameField;
        
        private int SupervisorStaffIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID
        {
            get
            {
                return this.BookIDField;
            }
            set
            {
                this.BookIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EmailSent
        {
            get
            {
                return this.EmailSentField;
            }
            set
            {
                this.EmailSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobCostCentre
        {
            get
            {
                return this.JobCostCentreField;
            }
            set
            {
                this.JobCostCentreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> JobDate
        {
            get
            {
                return this.JobDateField;
            }
            set
            {
                this.JobDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobDetails
        {
            get
            {
                return this.JobDetailsField;
            }
            set
            {
                this.JobDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tna.SAllocatePlus.CommonShared.Dto.JobStaffDto[] JobStaffList
        {
            get
            {
                return this.JobStaffListField;
            }
            set
            {
                this.JobStaffListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tna.SAllocatePlus.CommonShared.JobStageEnum JobStage
        {
            get
            {
                return this.JobStageField;
            }
            set
            {
                this.JobStageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> JobTime
        {
            get
            {
                return this.JobTimeField;
            }
            set
            {
                this.JobTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteAddress
        {
            get
            {
                return this.SiteAddressField;
            }
            set
            {
                this.SiteAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName
        {
            get
            {
                return this.SiteNameField;
            }
            set
            {
                this.SiteNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffRequired
        {
            get
            {
                return this.StaffRequiredField;
            }
            set
            {
                this.StaffRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorName
        {
            get
            {
                return this.SupervisorNameField;
            }
            set
            {
                this.SupervisorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupervisorStaffID
        {
            get
            {
                return this.SupervisorStaffIDField;
            }
            set
            {
                this.SupervisorStaffIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStaffDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class JobStaffDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookIDField;
        
        private bool IsStaffConfirmedField;
        
        private bool IsSupervisorField;
        
        private int JobStaffIDField;
        
        private int StaffIDField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private System.Nullable<System.TimeSpan> StartTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID
        {
            get
            {
                return this.BookIDField;
            }
            set
            {
                this.BookIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStaffConfirmed
        {
            get
            {
                return this.IsStaffConfirmedField;
            }
            set
            {
                this.IsStaffConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSupervisor
        {
            get
            {
                return this.IsSupervisorField;
            }
            set
            {
                this.IsSupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobStaffID
        {
            get
            {
                return this.JobStaffIDField;
            }
            set
            {
                this.JobStaffIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffID
        {
            get
            {
                return this.StaffIDField;
            }
            set
            {
                this.StaffIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailRequestDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class SendEmailRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentField;
        
        private string CostCentreField;
        
        private int[] JobListField;
        
        private int[] StaffListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCentre
        {
            get
            {
                return this.CostCentreField;
            }
            set
            {
                this.CostCentreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] JobList
        {
            get
            {
                return this.JobListField;
            }
            set
            {
                this.JobListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] StaffList
        {
            get
            {
                return this.StaffListField;
            }
            set
            {
                this.StaffListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobAvailabilityDto", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared.Dto")]
    public partial class JobAvailabilityDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookIDField;
        
        private System.Nullable<bool> IsAvailableField;
        
        private int StaffIDField;
        
        private string StaffNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookID
        {
            get
            {
                return this.BookIDField;
            }
            set
            {
                this.BookIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffID
        {
            get
            {
                return this.StaffIDField;
            }
            set
            {
                this.StaffIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffName
        {
            get
            {
                return this.StaffNameField;
            }
            set
            {
                this.StaffNameField = value;
            }
        }
    }
}
namespace Tna.SAllocatePlus.CommonShared
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStageEnum", Namespace="http://schemas.datacontract.org/2004/07/Tna.SAllocatePlus.CommonShared")]
    public enum JobStageEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inquiry = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tentative = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Booked = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LockIn = 4,
    }
}


